# playlists.properties
# add or remove new YouTube playlist entries (playlist url) here in the following manner!

playlist_urls=https://www.youtube.com/playlist?list=PLSG9IRx05GOn-ioDWMw5-92PsbPi-MHSH
playlist_urls=https://www.youtube.com/playlist?list=PLSG9IRx05GOlqnHGUm2bYVi2KPXYC_lTg